# Generated by Django 3.1.2 on 2020-10-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapi', '0003_auto_20201013_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
