# Generated by Django 3.1.2 on 2020-10-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapi', '0006_auto_20201015_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
