# Generated by Django 3.1.2 on 2021-01-18 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tradeapi', '0007_inventory_money'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.RemoveField(
            model_name='currency',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='money',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='reserved_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='item',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='price',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='price',
            name='sell',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='trade_type',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='date',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=8, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='tradeapi.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=8, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='tradeapi.currency'),
        ),
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='entry_quantity',
            field=models.IntegerField(verbose_name='Requested quantity'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='tradeapi.item'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(verbose_name='Current quantity'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price', to='tradeapi.currency'),
        ),
        migrations.AlterField(
            model_name='price',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='tradeapi.item'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade', to='tradeapi.item'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist', to='tradeapi.item'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
